version: '3.9' # optional since v1.27.0
services:
  api-crud-nest:
    image: api-crud-nest-image
    container_name: api-crud-nest-container
    build: .
    ports:
      - '5000:3000'
    environment:
      NODE_ENV: production
      DB_NAME: Prueba
      DB_PORT: 1433
      DB_USERNAME: diego.acevedo
      DB_PASSWORD: Medellin1*
      # DB_HOST: localhost
      DB_HOST: host.docker.internal
      DB_DATABASE: Prueba
      DB_TIMEOUT: 30000
